# Generated by Django 4.2.1 on 2023-05-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='rotation',
            field=models.FloatField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
