# Generated by Django 4.2.1 on 2023-05-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_square_rotation'),
    ]

    operations = [
        migrations.RemoveField(
            
            model_name='square',
            name='rotatio',
        ),
        migrations.AlterField(
            model_name='square',
            name='rotation',
            field=models.FloatField(),
        ),
    ]
